[package]
name = "build-push-action-test"
version = "0.1.0"
authors = ["x <x>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
